version: '3'
services:
  api:
    build: .
    volumes:
      - ./src:/app/src
      - ../../node_modules:/app/node_modules
    ports:
      - '5000:5000'
    links:
      - mongo
      - fixtures
    env_file:
      - development.env
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=riddler
    volumes:
      - ../../db-seed:/docker-entrypoint-initdb.d
    ports:
      - '27017:27017'
  fixtures:
    image: nginx:latest
    volumes:
      - ./__fixtures__:/usr/share/nginx/html/
    ports:
      - '8080:80'
    environment:
      - NGINX_PORT=80
