name: CI

on:
  pull_request:
    branches: [master]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Test backend package
        run: yarn workspace @comic-surfer/backend run test
