name: Fly Deploy

on:
  push:
    branches: [master]
    paths:
      - 'packages/backend/**'
      - 'Dockerfile'
      - 'fly.toml'

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Test backend package
        run: yarn workspace @comic-surfer/backend run test

  deploy:
    needs: jest
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy to fly
        uses: superfly/flyctl-actions@1.1
        with:
          args: 'deploy'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
